//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adventurechallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public int ChallengeNummer { get; set; }
        public string ChallengeBeschrijving { get; set; }
        public Nullable<int> ChallengeMoeilijkheid { get; set; }
        public Nullable<int> ChallengeKosten { get; set; }
        public Nullable<int> ChallengeAantalMensen { get; set; }
    }
}
